In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 6)
arr

array([0, 1, 2, 3, 4, 5])

In [4]:
nd = np.zeros((5,9), dtype = int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
nd1 = np.ones((10,10), dtype = int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### Numpy Funtions

In [6]:
np.random.rand(2)

array([0.38682048, 0.42365682])

In [16]:
np.random.rand(3)

array([0.67891626, 0.38604894, 0.21481586])

In [17]:
np.random.rand(2,3)

array([[0.45633393, 0.30916973, 0.94315794],
       [0.44526499, 0.17692997, 0.64329988]])

In [23]:
np.random.randint(3)

2

In [26]:
np.random.randint(2,10)

7

In [29]:
np.random.randint(2,10,4)

array([8, 2, 7, 3], dtype=int32)

In [30]:
np.random.randint(-30,20,10)

array([  5,  -5,   3,  -7, -14, -22,  -3,  18,  -7, -28], dtype=int32)

In [31]:
np.random.randint(10,40,(10,10))

array([[33, 15, 36, 12, 11, 21, 21, 17, 31, 29],
       [21, 31, 15, 20, 31, 32, 24, 20, 35, 19],
       [38, 22, 21, 14, 36, 19, 32, 10, 29, 25],
       [15, 11, 38, 36, 10, 38, 20, 25, 30, 17],
       [20, 14, 22, 38, 33, 33, 25, 18, 38, 30],
       [23, 25, 33, 11, 22, 13, 16, 33, 25, 12],
       [25, 27, 13, 19, 20, 21, 14, 19, 18, 24],
       [20, 21, 30, 27, 17, 15, 18, 28, 35, 20],
       [14, 13, 32, 26, 29, 28, 37, 16, 19, 12],
       [28, 18, 26, 35, 25, 18, 23, 25, 13, 38]], dtype=int32)

In [32]:
m = np.random.randint(10,40,(10,10))
m

array([[39, 38, 27, 33, 15, 37, 30, 25, 24, 24],
       [39, 30, 21, 26, 29, 23, 12, 16, 10, 12],
       [10, 13, 12, 16, 32, 21, 30, 38, 13, 10],
       [31, 33, 39, 32, 23, 13, 12, 11, 34, 31],
       [21, 24, 16, 36, 20, 10, 11, 23, 15, 16],
       [29, 11, 18, 35, 37, 27, 28, 16, 30, 18],
       [23, 25, 23, 22, 32, 19, 12, 24, 10, 15],
       [30, 29, 25, 32, 28, 37, 26, 25, 26, 14],
       [11, 28, 37, 18, 30, 27, 31, 36, 12, 17],
       [16, 38, 23, 11, 24, 32, 34, 10, 36, 31]], dtype=int32)

In [33]:
arr

array([0, 1, 2, 3, 4, 5])

In [34]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [36]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [37]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

### Slicing

In [38]:
m

array([[39, 38, 27, 33, 15, 37, 30, 25, 24, 24],
       [39, 30, 21, 26, 29, 23, 12, 16, 10, 12],
       [10, 13, 12, 16, 32, 21, 30, 38, 13, 10],
       [31, 33, 39, 32, 23, 13, 12, 11, 34, 31],
       [21, 24, 16, 36, 20, 10, 11, 23, 15, 16],
       [29, 11, 18, 35, 37, 27, 28, 16, 30, 18],
       [23, 25, 23, 22, 32, 19, 12, 24, 10, 15],
       [30, 29, 25, 32, 28, 37, 26, 25, 26, 14],
       [11, 28, 37, 18, 30, 27, 31, 36, 12, 17],
       [16, 38, 23, 11, 24, 32, 34, 10, 36, 31]], dtype=int32)

In [41]:
b = np.random.randint(10,20,(5,4))
b

array([[15, 18, 14, 15],
       [10, 16, 18, 15],
       [10, 15, 14, 16],
       [11, 13, 12, 15],
       [14, 14, 14, 18]], dtype=int32)

In [42]:
b[:]

array([[15, 18, 14, 15],
       [10, 16, 18, 15],
       [10, 15, 14, 16],
       [11, 13, 12, 15],
       [14, 14, 14, 18]], dtype=int32)

In [43]:
b[1:4]

array([[10, 16, 18, 15],
       [10, 15, 14, 16],
       [11, 13, 12, 15]], dtype=int32)

In [44]:
b

array([[15, 18, 14, 15],
       [10, 16, 18, 15],
       [10, 15, 14, 16],
       [11, 13, 12, 15],
       [14, 14, 14, 18]], dtype=int32)

In [45]:
b[-1:]

array([[14, 14, 14, 18]], dtype=int32)

In [46]:
b[:-1]

array([[15, 18, 14, 15],
       [10, 16, 18, 15],
       [10, 15, 14, 16],
       [11, 13, 12, 15]], dtype=int32)

In [47]:
b[-5,-3]

np.int32(18)

In [48]:
np.random.randint(10,20,(4,4))

array([[15, 12, 16, 15],
       [12, 15, 12, 12],
       [10, 15, 17, 18],
       [14, 11, 11, 13]], dtype=int32)

In [49]:
b

array([[15, 18, 14, 15],
       [10, 16, 18, 15],
       [10, 15, 14, 16],
       [11, 13, 12, 15],
       [14, 14, 14, 18]], dtype=int32)

In [50]:
b[-4,-2]

np.int32(18)

In [51]:
b[-4:2]

array([[10, 16, 18, 15]], dtype=int32)

### Operations

In [53]:
a = np.random.randint(10,20,10)
a

array([10, 12, 13, 10, 18, 15, 15, 13, 16, 16], dtype=int32)

In [54]:
id(a)

2432381672816

In [55]:
arr

array([0, 1, 2, 3, 4, 5])

In [56]:
arr2 = np.random.randint(0,100,(10,10))

In [57]:
arr2

array([[93, 94, 29, 61, 95, 90, 96, 10, 72, 23],
       [92, 76, 62, 25, 30, 47, 38, 13, 81, 91],
       [33, 42, 48, 95, 17, 88, 16, 21, 48, 70],
       [73, 57, 67, 22, 95, 26, 80, 16, 49, 42],
       [23, 14, 50, 44,  7, 51, 55,  3, 35, 91],
       [28,  4, 48, 18, 87, 42, 69, 23, 51, 31],
       [21, 57, 33, 34, 97, 92, 25, 27, 37, 82],
       [23, 73, 25, 94, 86, 85, 14, 36, 88, 34],
       [21, 30, 50,  0, 49,  0, 51, 58, 85, 38],
       [25, 39, 98, 27, 38, 18, 85, 89, 53, 72]], dtype=int32)

In [58]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [59]:
arr[:4]

array([0, 1, 2, 3])

In [60]:
arr2[:]

array([[93, 94, 29, 61, 95, 90, 96, 10, 72, 23],
       [92, 76, 62, 25, 30, 47, 38, 13, 81, 91],
       [33, 42, 48, 95, 17, 88, 16, 21, 48, 70],
       [73, 57, 67, 22, 95, 26, 80, 16, 49, 42],
       [23, 14, 50, 44,  7, 51, 55,  3, 35, 91],
       [28,  4, 48, 18, 87, 42, 69, 23, 51, 31],
       [21, 57, 33, 34, 97, 92, 25, 27, 37, 82],
       [23, 73, 25, 94, 86, 85, 14, 36, 88, 34],
       [21, 30, 50,  0, 49,  0, 51, 58, 85, 38],
       [25, 39, 98, 27, 38, 18, 85, 89, 53, 72]], dtype=int32)

In [61]:
arr2[0:5]

array([[93, 94, 29, 61, 95, 90, 96, 10, 72, 23],
       [92, 76, 62, 25, 30, 47, 38, 13, 81, 91],
       [33, 42, 48, 95, 17, 88, 16, 21, 48, 70],
       [73, 57, 67, 22, 95, 26, 80, 16, 49, 42],
       [23, 14, 50, 44,  7, 51, 55,  3, 35, 91]], dtype=int32)

In [62]:
arr2[1,4]

np.int32(30)

In [67]:
arr2[1,3]

np.int32(25)

In [68]:
arr2

array([[93, 94, 29, 61, 95, 90, 96, 10, 72, 23],
       [92, 76, 62, 25, 30, 47, 38, 13, 81, 91],
       [33, 42, 48, 95, 17, 88, 16, 21, 48, 70],
       [73, 57, 67, 22, 95, 26, 80, 16, 49, 42],
       [23, 14, 50, 44,  7, 51, 55,  3, 35, 91],
       [28,  4, 48, 18, 87, 42, 69, 23, 51, 31],
       [21, 57, 33, 34, 97, 92, 25, 27, 37, 82],
       [23, 73, 25, 94, 86, 85, 14, 36, 88, 34],
       [21, 30, 50,  0, 49,  0, 51, 58, 85, 38],
       [25, 39, 98, 27, 38, 18, 85, 89, 53, 72]], dtype=int32)

In [69]:
arr2[-5,5]

np.int32(42)

In [72]:
arr2[-1,-2]

np.int32(53)

In [76]:
print(arr2)

[[93 94 29 61 95 90 96 10 72 23]
 [92 76 62 25 30 47 38 13 81 91]
 [33 42 48 95 17 88 16 21 48 70]
 [73 57 67 22 95 26 80 16 49 42]
 [23 14 50 44  7 51 55  3 35 91]
 [28  4 48 18 87 42 69 23 51 31]
 [21 57 33 34 97 92 25 27 37 82]
 [23 73 25 94 86 85 14 36 88 34]
 [21 30 50  0 49  0 51 58 85 38]
 [25 39 98 27 38 18 85 89 53 72]]


In [77]:
print(arr2[::-1]) # This reverses the rows of the matrix — last row comes first, first row comes

[[25 39 98 27 38 18 85 89 53 72]
 [21 30 50  0 49  0 51 58 85 38]
 [23 73 25 94 86 85 14 36 88 34]
 [21 57 33 34 97 92 25 27 37 82]
 [28  4 48 18 87 42 69 23 51 31]
 [23 14 50 44  7 51 55  3 35 91]
 [73 57 67 22 95 26 80 16 49 42]
 [33 42 48 95 17 88 16 21 48 70]
 [92 76 62 25 30 47 38 13 81 91]
 [93 94 29 61 95 90 96 10 72 23]]


In [79]:
# This reverses the rows and takes every 2nd row — from bottom to top, skipping one row in between.
print(arr2[::-2])

[[25 39 98 27 38 18 85 89 53 72]
 [23 73 25 94 86 85 14 36 88 34]
 [28  4 48 18 87 42 69 23 51 31]
 [73 57 67 22 95 26 80 16 49 42]
 [92 76 62 25 30 47 38 13 81 91]]


In [80]:
# This reverses the rows and takes every 3rd row — from bottom to top, skipping two rows in between.
print(arr2[::-3])

[[25 39 98 27 38 18 85 89 53 72]
 [21 57 33 34 97 92 25 27 37 82]
 [73 57 67 22 95 26 80 16 49 42]
 [93 94 29 61 95 90 96 10 72 23]]


In [81]:
# This slices rows from index 0 to 9 (inclusive), taking every 3rd row — normal order.
print(arr2[0:10:3])

[[93 94 29 61 95 90 96 10 72 23]
 [73 57 67 22 95 26 80 16 49 42]
 [21 57 33 34 97 92 25 27 37 82]
 [25 39 98 27 38 18 85 89 53 72]]


In [82]:
arr

array([0, 1, 2, 3, 4, 5])

In [83]:
arr.max()

np.int64(5)

In [84]:
arr.min()

np.int64(0)

In [85]:
arr.mean()

np.float64(2.5)

In [86]:
print(arr.reshape(3,2))

[[0 1]
 [2 3]
 [4 5]]


In [87]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [89]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

### Indexing

In [90]:
mat = np.arange(0,100).reshape(10,10)

In [91]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [92]:
row=4
col=5

In [93]:
col

5

In [94]:
row

4

In [95]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
mat[row,col]

np.int64(45)

In [97]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [98]:
col=6

In [99]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [100]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [101]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [102]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [103]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [104]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [105]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [106]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [107]:
row

4

In [108]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [109]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [110]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [111]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [112]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [113]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [114]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [115]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [116]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [117]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [119]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [120]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [121]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [122]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [123]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [124]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [125]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [126]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

### Masking
#### Masking means applying a condition to a NumPy array to filter/select elements based on True/False values.
**How does it work?**
- Create a condition: mat > 50 → returns a Boolean mask of the same shape as mat
- Apply mask: mat[mat > 50] → returns only the values where the condition is True

In [127]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [128]:
id(mat)

2432381672240

In [129]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [130]:
mat[mat<40]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [131]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [132]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [133]:
mat[mat==50]

array([50])

In [134]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [135]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [136]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [137]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [139]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [142]:
a4 = mat[mat==50]
a4

array([50])